### PR TITLE
Implementation of FetchJwtSvid method, DefaultWorkloadApiClient class

### PR DESCRIPTION
**Pull request by glaucimar**
- Method implemenation.
- Creation of FetchJwtSvidError.
- Added a file for the tests of JWT related methods of DefaultWorkloadApiClient class.
- Added tests for fetch_jwt_svid method.

This **partially** addresses issue #62 .

### CODE REVIEW

**Comment by maxlambrecht** [comment]
Do a rebase with master.

**Comment by glaucimar** [comment]
This was submitted before the merge.. I will work on the rebase now.

**Comment by maxlambrecht** [comment]
Hi Glaucimar, your PR now includes commits that are changes from other PRs already merged to master.

**Comment by glaucimar** [comment]
Folks.. there was a big issue with my rebase... and my squash attempt did not work as well. I will open another pull request.. abandoning this one.

**Pull request closed without merging**
